### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by ywyue** [ManyiLi12345/D2IM-Net#1]
Hi, thanks for your great work! I am wondering if you have plan to release your pretrained model 'best_model.pt.tar'? Currently, I only find the camera model ('CAMmodel.pt.tar') in the provided google drive.

**Comment by ManyiLi12345** [comment]
Hi I just uploaded the pre-trained model into the google drive folder.  Please pay attention to the train/test split for the training if you need to compare with the other methods.

**Comment by ywyue** [comment]
> Hi I just uploaded the pre-trained model into the google drive folder. Please pay attention to the train/test split for the training if you need to compare with the other methods.

Thanks!

**Comment by YangPeppa** [comment]
I can't decompress the compressed file you uploaded, as if the compressed file is damaged. @ManyiLi12345
