### ISSUE TITLE
ECD implementation

### ISSUE THREAD

**Issue by samiarshad** [ManyiLi12345/D2IM-Net#2]
Hi,

Thanks for sharing your work.
Would it be possible to share the implementation/provide some details about the Edge Chamfer Distance? How did you filter out the edge points? How did you get the normal vector between p1 and p2?

Thanks

**Comment by ManyiLi12345** [comment]
Hi, as described in the paper, we select the edge points by calculating the "edgeness". Please refer to the formulation in Section 4.1 for the details. 

The normals are estimated from the reconstructed mesh, which is extracted from the implicit field using MarchingCube. I didn't implement the normal estimation but used a meshlab script to prepare the points and normals. You can directly calculate the CD on the two sets of selected edge points.

**Comment by samiarshad** [comment]
Thanks for your response.
